const DEFAULT_TITLE = "Next Template";
const DEFAULT_DESCRIPTION = "Next Template";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "Antarctic Solutions Inc.",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["next", "boilerplate"],
  DEFAULT_SITE_NAME: "Next Template",
  DEFAULT_BASE_URL: "",
  DEFAULT_PREVIEW_IMG: "",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "",
};

export default CONSTANTS;
